name: SurvieHardcore
version: 1.0
main: fr.springg.surviehardcore.Main
author: Spring_g
commands:
  custom:
    description: Spawn des mobs customs
    permission: custom.perm
  kit:
    description: Commande de Kit.
  worlds:
    description: Worlds
    permission: worlds.perm
  customnpc:
    permission: npc.perm
    description: NPC
  menu:
    description: Menu
  hub:
    description: Hub
  hologram:
    permission: hologram.perm
    description: Holograms